#!/bin/bash

###############################################################################
# Storage Health Monitor
###############################################################################
#Do not change anything below
CONFIG_FILE="$(dirname "$0")/storage-health-monitor.conf"
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
source "$SCRIPT_DIR/lib/load.sh"

main()
{
    parse_args "$@"

    init

    #
    #collect disk info
    #
if [[ "$INVENTORY_ONLY" == "true" ]]; then
    init
    collect_inventory
    exit 0
fi
    #
    # Collect findings
    #
if [[ "$HP_RAID_ENABLED" == "yes" ]]; then
    collect_hp_findings
fi

if [[ "$SMART_ENABLED" == "yes" ]]; then
    collect_smart_findings
fi

    notify_findings

    #
    # Display findings
    #
    show_findings
}

main "$@"
