#!/bin/bash

###############################################################################
# Configuration for providers
###############################################################################

# HP_RAID - ssacli needed
# SMART - smartctl needed
# Use yes/no
HP_RAID_ENABLED="yes"
SMART_ENABLED="no"

###############################################################################
# Configuration for notifications
###############################################################################

# none      → no external notification
# apprise   → send through Apprise
# telegram  → send directly through Telegram Bot API

NOTIFY_METHOD="none"
APPRISE_URL=""

TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
###############################################################################
# Storage Health Monitor
###############################################################################
#Do not change anything below

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
source "$SCRIPT_DIR/lib/load.sh"

main()
{
    parse_args "$@"

    init

    #
    #collect disk info
    #
if [[ "$INVENTORY_ONLY" == "true" ]]; then
    init
    collect_inventory
    exit 0
fi
    #
    # Collect findings
    #
if [[ "$HP_RAID_ENABLED" == "yes" ]]; then
    collect_hp_findings
fi

if [[ "$SMART_ENABLED" == "yes" ]]; then
    collect_smart_findings
fi

    notify_findings

    #
    # Display findings
    #
    show_findings
}

main "$@"
